task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from tasks import views

urlpatterns = [
	path("", views.TaskListView.as_view(), name="index"),
	path("tags/", views.TagListView.as_view(), name="tags"),
	path("tags/create/", views.TagCreateView.as_view(), name="create-tag"),
	path("tags/<int:pk>/update", views.TagUpdateView.as_view(), name="tag-update"),
	path("tags/<int:pk>/delete", views.TagDeleteView.as_view(), name="tag-delete"),
	path("tasks/create/", views.TaskCreateView.as_view(), name="create-task"),
	path("tasks/<int:pk>/update", views.TaskUpdateView.as_view(), name="task-update"),
	path("tasks/<int:pk>/delete", views.TaskDeleteView.as_view(), name="task-delete"),
	path("tasks/<int:pk>/complete", views.task_complete, name="task-complete"),
	path("tasks/<int:pk>/undo", views.task_undo, name="task-undo"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "tasks"

tasks/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
	name = models.CharField(max_length=100)

	class Meta:
		verbose_name = "Tag"
		verbose_name_plural = "Tags"
		ordering = ["name"]

	def __str__(self):
		return self.name


class Task(models.Model):
	content = models.CharField(max_length=1024)
	created_at = models.DateTimeField(auto_now_add=True)
	deadline = models.DateTimeField()
	done = models.BooleanField()
	tags = models.ManyToManyField(Tag, related_name="tasks")

	class Meta:
		verbose_name = "Task"
		verbose_name_plural = "Tasks"
		ordering = ["done", "created_at"]

	def get_tags(self):
		tags_list = list(self.tags.all().values_list("name", flat=True))
		return ", ".join(tags_list)

	def __str__(self):
		return self.content

tasks/forms.py
from django import forms

from tasks.models import Task, Tag


class TaskCreateForm(forms.ModelForm):
	content = forms.CharField(
		max_length=1024,
		required=True,
		widget=forms.TextInput(
			attrs={
				"class": "form-control mb-3",
			}
		)
	)

	deadline = forms.DateTimeField(
		required=True,
		widget=forms.DateTimeInput(
			attrs={
				"class": "form-control mb-3",
				"type": "datetime-local"
			}
		)
	)

	done = forms.BooleanField(
		required=False,
		initial=False,
		widget=forms.CheckboxInput(
			attrs={
				"class": "hidden"
			}
		)
	)

	tags = forms.ModelMultipleChoiceField(
		queryset=Tag.objects.all(),
		widget=forms.CheckboxSelectMultiple(
			attrs={
				"class": "form-check mb-3",
			}
		)
	)

	class Meta:
		model = Task
		fields = ("content", "deadline", "done", "tags")

tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from tasks.forms import TaskCreateForm
from tasks.models import Task, Tag


class TaskListView(generic.ListView):
	model = Task
	template_name = "tasks/index.html"


class TaskCreateView(generic.CreateView):
	model = Task
	form_class = TaskCreateForm
	success_url = reverse_lazy("tasks:index")


class TaskUpdateView(generic.UpdateView):
	model = Task
	fields = "__all__"
	success_url = reverse_lazy("tasks:index")


class TaskDeleteView(generic.DeleteView):
	model = Task
	success_url = reverse_lazy("tasks:index")
	template_name = "tasks/task_confirm_delete.html"


def task_complete(request, pk):
	task = Task.objects.get(pk=pk)
	task.done = True
	task.save()
	return redirect("tasks:index")


def task_undo(request, pk):
	task = Task.objects.get(pk=pk)
	task.done = False
	task.save()
	return redirect("tasks:index")


class TagListView(generic.ListView):
	model = Tag


class TagCreateView(generic.CreateView):
	model = Tag
	fields = "__all__"
	success_url = reverse_lazy("tasks:tags")


class TagUpdateView(generic.UpdateView):
	model = Tag
	fields = "__all__"
	success_url = reverse_lazy("tasks:tags")


class TagDeleteView(generic.DeleteView):
	model = Tag
	success_url = reverse_lazy("tasks:tags")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Goal Getter</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
{#  bootstrap #}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
  <!-- Add additional CSS in a static file -->
  {% load static %}
  <link rel="stylesheet"
        href="{% static 'css/styles.css' %}">
  <!-- Font Awesome -->
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
  />
  <!-- Google Fonts -->
  <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
  />
  <!-- MDB -->
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css"
      rel="stylesheet"
  />
  {% block head %}
  {% endblock %}
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>

{#  bootstrap #}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<!-- MDB -->
<script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"
></script>
</body>
</html>

templates/includes/go_back_button.html
    <a href="javascript:history.go(-1)"
       class="btn btn-dark">Go back</a>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mt-5">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link"
             href="?{% query_transform request page=page_obj.previous_page_number %}"
             aria-label="Previous">
            <span aria-hidden="true">Previous</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
        <span class="page-link"
              aria-hidden="true">Previous</span>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"
              aria-current="page">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link"
               href="?{% query_transform request page=i %}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link"
             href="?{% query_transform request page=page_obj.next_page_number %}"
             aria-label="Next">
            <span aria-hidden="true">Next</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
        <span class="page-link"
              aria-hidden="true">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/sidebar.html
<div class="sidebar-nav list-group mt-5">
  <a href="{% url 'tasks:index' %}" class="btn btn-link"><div class="list-group-item">Home</div></a>
  <a href="{% url 'tasks:tags' %}" class="btn btn-link"><div class="list-group-item">Tags</div></a>
</div>

templates/tasks/index.html
{% extends "base.html" %}



{% block content %}
  <h1 class="mt-5 w-50">TODO List
    <a class="btn btn-primary float-end" href="{% url 'tasks:create-task' %}">Add Task</a>
  </h1>
  <hr class="w-50">
  {% if task_list %}
    {% for task in task_list %}
      <div class="row w-100">
        <div class="col-sm-8">
          <h5 class="fw-bold">{{ task.content }}
            {% if task.done %}
              <span class="badge bg-success ms-3">Done</span>
              <a class="btn btn-sm btn-grey float-end" href="{% url 'tasks:task-undo' task.id %}">Undo</a>
            {% else %}
              <span class="badge bg-danger ms-3">Not Done</span>
              <a class="btn btn-sm btn-success float-end" href="{% url 'tasks:task-complete' task.id %}">Complete</a>
            {% endif %}
          </h5>
          <p class="text-muted">Created: {{ task.created_at }} <span class="text-danger">Dealine: {{ task.deadline }}</span></p>
          <h6 class="text-muted">Tags: {{ task.get_tags }}</h6>
          <p class="mt-3">
            <a class="btn btn-sm btn-outline-dark" href="{% url 'tasks:task-update' task.id %}">Update</a>
            <a class="btn btn-sm btn-outline-danger" href="{% url 'tasks:task-delete' task.id %}">Delete</a>
          </p>
        </div>
      </div>
      <hr class="w-75">
    {% endfor %}
  {% endif %}

{% endblock %}

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="ms-5 mt-5">
    <h1>Delete tag?</h1>
    <form action=""
          method="post">
      {% csrf_token %}

      <input type="submit"
             value="Yes"
             class="btn btn-danger">
      {% include "includes/go_back_button.html" %}
    </form>
  </div>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="mt-5">{{ object|yesno:"Update,Create" }} tag</h1>
  <hr class="w-75">
  <form class="w-75" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary mt-3">
    {% include "includes/go_back_button.html" %}
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}



{% block content %}
  <h1 class="mt-5 w-50">Tags
    <a class="btn btn-primary float-end"
       href="{% url 'tasks:create-tag' %}">Add Tag</a>
  </h1>
  <hr class="w-50">
  {% if tag_list %}
    <div class="row w-100">
      <div class="col-sm-8">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
          </thead>
          <tbody>
          {% for tag in tag_list %}
            <tr>
              <td>{{ tag.name }}</td>
              <td><a class="btn btn-sm btn-outline-grey" href="{% url 'tasks:tag-update' tag.id %}">Update</a></td>
              <td><a class="btn btn-sm btn-danger" href="{% url 'tasks:tag-delete' tag.id %}">Delete</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="ms-5 mt-5">
    <h1>Delete task?</h1>
    <form action=""
          method="post">
      {% csrf_token %}

      <input type="submit"
             value="Yes"
             class="btn btn-danger">
      {% include "includes/go_back_button.html" %}
    </form>
  </div>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="mt-5">{{ object|yesno:"Update,Create" }} task</h1>
  <hr class="w-75">
  <form class="w-75" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary mt-3">
    {% include "includes/go_back_button.html" %}
  </form>
{% endblock %}